export const awards = [
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "In-depth Enterprise and Investigative Reporting (First place)",
    article:
      "As Some Oklahoma Churches Push Vaccines, Others Sow Misinformation, Doubt",
    year: 2022,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "Government Reporting (First place)",
    article:
      "No Comment: In Oklahoma’s Legislature, Public Rarely Given Chance to Weigh In",
    year: 2022,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "Diversity Reporting (Third place)",
    article:
      "Redistricting: Weighing the Impact of Splitting Oklahoma’s Largest Hispanic Community (co-byline)",
    year: 2022,
    link: "Read More",
  },
  {
    organization: "Great Plains Journalism Awards",
    award: "Great Plains Newspaper Writer of the Year (Finalist)",
    article: "Multiple articles",
    year: 2022,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "Criminal Justice Reporting (First Place)",
    article:
      "Twenty Years After It Became a Crime, Racial Profiling Charges Remain Scarce",
    year: 2021,
    link: "Read More",
  },
  {
    organization: "Great Plains Journalism Awards",
    award: "Great Plains Newspaper Writer of the Year",
    article: "Multiple articles",
    year: 2021,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "Best of the Best: Reporter of the Year",
    article: "Multiple Articles",
    year: 2020,
    link: "Read More",
  },
  {
    organization: "Institute for Nonprofit News",
    award: "Community Champion Award (Honorable Mention)",
    article: "A Digital Memorial to Oklahomans Who Died from COVID-19",
    year: 2020,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "General News Reporting (First Place)",
    article: "Hospitals Sue Thousands Each Year Over Unpaid Medical Bills",
    year: 2020,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award:
      "Science, Technology, Health and Environmental Reporting (First Place)",
    article: "Multiple articles",
    year: 2020,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "Government Reporting (Second Place)",
    article: "The Sway of Lobbyists (co-byline)",
    year: 2020,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "In-depth Enterprise and Investigative Reporting (First place)",
    article: "Political Muscle: Money and Special Interests (Co-byline)",
    year: 2019,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "Multimedia (Second Place)",
    article: "Teacher Walkout (Co-byline)",
    year: 2019,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "In-depth Enterprise and Investigative Reporting (First place)",
    article: "Inside Democracy Package (Co-byline)",
    year: 2018,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "Special Report/Enterprise Reporting (First Place)",
    article: "Inside Democracy Package (Co-byline)",
    year: 2018,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "Multimedia (Second Place)",
    article: "Special Legislative Session Coverage",
    year: 2018,
    link: "Read More",
  },
  {
    organization: "Great Plains Journalism Awards",
    award: "Project Investigative Reporting (Finalist)",
    article: "Inside Democracy Package (Co-byline)",
    year: 2018,
    link: "Read More",
  },
  {
    organization: "Oklahoma Society of Professional Journalists",
    award: "Election Reporting (First Place)",
    article: "Multiple Articles (Co-byline)",
    year: 2018,
    link: "Read More",
  },
];
