// webProjects.js

export const webProjects = [
  {
    id: 1,
    title: "Open Cabinet: Financial Disclosure Tracker",
    type: "Professional",
    tag: "Data Journalism",
    workInProgress: false,
    image: null,
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "D3.js",
    ],
    createdDate: "2026",
    description:
      "Financial disclosure tracker for U.S. executive branch officials. 617 pages of OGE filings parsed into searchable data with $2.9B in assets tracked. Interactive D3.js visualizations for asset breakdowns.",
    githubLink: "https://github.com/tbrown034/open-cabinet",
    siteLink: "https://open-cabinet.org",
  },
  {
    id: 2,
    title: "Capitol Releases: Congressional Press Release Tracker",
    type: "Professional",
    tag: "Data Journalism",
    workInProgress: false,
    image: null,
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
    ],
    createdDate: "2026",
    description:
      "Congressional press release tracker and analyzer monitoring all 100 U.S. senators. Aggregates official communications into per-senator intelligence reports with trend analysis.",
    githubLink: "https://github.com/tbrown034/capitol-releases",
    siteLink: "https://capitolreleases.com",
  },
  {
    id: 3,
    title: "News Pulse: Open-Source News Monitor",
    type: "Professional",
    tag: "OSINT & Aggregation",
    workInProgress: false,
    image: null,
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
    ],
    createdDate: "2025",
    description:
      "Real-time news intelligence dashboard. Aggregates breaking stories with geopolitical context, trending keywords and region filtering.",
    githubLink: "https://github.com/tbrown034/news-alert",
    siteLink: "https://news-pulse.org",
  },
  {
    id: 4,
    title: "Keith Brown DDS: Dental Practice Website",
    type: "Professional",
    tag: "SEO & Marketing",
    workInProgress: false,
    image: "/images/kabdds-screenshot-oct25.png",
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Google Ads",
      "Vercel",
    ],
    createdDate: "2024",
    description:
      "Production dental practice website driving real patient traffic via active Google Ads campaigns. More than tripled new patient bookings since launch. Admin dashboard integrates GA4, CallRail and Google Business Profile analytics.",
    githubLink: "https://github.com/tbrown034/kab-dentist",
    siteLink: "https://keithbrowndds.com/",
  },
  {
    id: 5,
    title: "Caught Up Yet: Spoiler-Free Sports Chat",
    type: "Personal",
    tag: "Real-Time & Auth",
    workInProgress: true,
    image: null,
    technologies: [
      "Next.js",
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Supabase",
      "PostgreSQL",
    ],
    createdDate: "2026",
    description:
      "Spoiler-free sports app for fans watching games on delay. Create rooms, invite friends and family and chat about games without scores being revealed. Filters alerts by team and sport with Supabase auth and real-time PostgreSQL.",
    githubLink: "https://github.com/tbrown034/caught-up-yet",
    siteLink: "https://caught-up-yet.vercel.app",
  },
  {
    id: 6,
    title: "Second Brain: Personal Knowledge Base",
    type: "Personal",
    tag: "Data Pipelines & AI",
    workInProgress: true,
    image: null,
    technologies: [
      "TypeScript",
      "React",
      "Next.js",
      "Playwright",
      "Anthropic API",
    ],
    createdDate: "2026",
    description:
      "Processes 200,000+ personal records from a dozen data sources through TypeScript data pipelines with deduplication and normalization. Features an AI chat assistant, semantic search and visualization dashboards with a Tauri desktop wrapper.",
    githubLink: null,
    siteLink: null,
  },
  {
    id: 7,
    title: "AI Model Arena: Side-by-Side LLM Comparison",
    type: "Personal",
    tag: "Multi-Provider AI",
    workInProgress: true,
    image: null,
    technologies: [
      "Next.js",
      "TypeScript",
      "Anthropic API",
      "OpenAI API",
      "Google Gemini API",
      "Grok API",
    ],
    createdDate: "2025",
    description:
      "Side-by-side AI comparison tool that sends one prompt to Claude, GPT, Gemini and Grok simultaneously. Includes AI-powered peer ranking, real-time cost tracking and a Fast vs. Frontier mode toggle.",
    githubLink: null,
    siteLink: "https://ai-model-arena-umber.vercel.app",
  },
  {
    id: 8,
    title: "sort(id): Media Ranking and Sharing Platform",
    type: "Hobby",
    tag: "Auth & Database",
    workInProgress: true,
    image: "/images/reflectyr-screenshot-aug11.png",
    technologies: [
      "Next.js",
      "NextAuth.js",
      "PostgreSQL",
      "TMDB API",
    ],
    createdDate: "2024",
    description:
      "Media ranking platform where users create and share ranked lists of movies, TV, books and anime. Built with drag-and-drop interfaces, TMDB API integration, NextAuth.js authentication and PostgreSQL persistence.",
    githubLink: null,
    siteLink: "https://reflectyr.vercel.app/",
  },
  {
    id: 9,
    title: "Food Xpiry: AI-Powered Grocery Expiration Tracker",
    type: "Hobby",
    tag: "AI Integration",
    workInProgress: true,
    image: "/images/expirty-screenshot-aug11.png",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "PostgreSQL (Neon)",
      "Prisma",
      "Anthropic AI API",
    ],
    createdDate: "2025",
    description:
      "Grocery tracker that reduces food waste using USDA FoodKeeper data and Anthropic API shelf-life estimates. Users log items, get storage tips and track expiration dates with PostgreSQL persistence via Neon.",
    githubLink: "https://github.com/tbrown034/food-xpiry",
    siteLink: "https://food-xpiry.vercel.app/",
  },
];
