// webProjects.js

export const webProjects = [
  {
    id: 1,
    title: "Keith Brown DDS: Dental Practice Website",
    type: "Professional",
    tag: "SEO & Marketing",
    workInProgress: false,
    image: "/images/kabdds-screenshot-oct25.png",
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Google Ads",
      "Python",
      "Clerk Auth",
      "Nodemailer",
    ],
    createdDate: "2024",

    description:
      "Production dental practice site that increased online bookings by 33%. Manage SEO and a $2,000/month Google Ads campaign. Admin dashboard integrates GA4, CallRail and Google Business Profile with real-time ad controls, a Python billing pipeline and an AI chat interface.",
    githubLink: "https://github.com/tbrown034/kab-dental",
    siteLink: "https://keithbrowndds.com/",
  },
  {
    id: 2,
    title: "Second Brain: Personal Knowledge Base",
    type: "Personal",
    tag: "Data Pipelines & AI",
    workInProgress: true,
    image: null,
    technologies: [
      "TypeScript",
      "React",
      "Next.js",
      "Playwright",
      "Anthropic API",
    ],
    createdDate: "2026",
    description:
      "Processes 200,000+ personal records from a dozen data sources through TypeScript data pipelines with deduplication and normalization. Features an AI chat assistant, semantic search and visualization dashboards with a Tauri desktop wrapper.",
    githubLink: null,
    siteLink: null,
  },
  {
    id: 3,
    title: "News Pulse: Open-Source Intelligence Dashboard",
    type: "Personal",
    tag: "OSINT & Aggregation",
    workInProgress: true,
    image: null,
    technologies: [
      "Next.js",
      "TypeScript",
      "Anthropic API",
      "RSS",
      "Bluesky API",
      "Tailwind CSS",
    ],
    createdDate: "2025",
    description:
      "Open-source news intelligence dashboard aggregating verified sources across RSS, Bluesky, Telegram, Reddit and YouTube. Features map-based monitoring, surge detection and tiered AI summarization via Claude.",
    githubLink: "https://github.com/tbrown034/news-alert",
    siteLink: "https://news-alert-eta.vercel.app",
  },
  {
    id: 4,
    title: "AI Model Arena: Side-by-Side LLM Comparison",
    type: "Personal",
    tag: "Multi-Provider AI",
    workInProgress: true,
    image: null,
    technologies: [
      "Next.js",
      "TypeScript",
      "Anthropic API",
      "OpenAI API",
      "Google Gemini API",
      "Grok API",
    ],
    createdDate: "2025",
    description:
      "Side-by-side AI comparison tool that sends one prompt to Claude, GPT, Gemini and Grok simultaneously. Includes AI-powered peer ranking, real-time cost tracking and a Fast vs. Frontier mode toggle.",
    githubLink: null,
    siteLink: "https://ai-model-arena-umber.vercel.app",
  },
  {
    id: 5,
    title: "sort(id): Media Ranking and Sharing Platform",
    type: "Hobby",
    tag: "Auth & Database",
    workInProgress: true,
    image: "/images/reflectyr-screenshot-aug11.png",
    technologies: [
      "Next.js",
      "NextAuth.js",
      "PostgreSQL",
      "TMDB API",
    ],
    createdDate: "2024",
    description:
      "Media ranking platform where users create and share ranked lists of movies, TV, books and anime. Built with drag-and-drop interfaces, TMDB API integration, NextAuth.js authentication and PostgreSQL persistence.",
    githubLink: null,
    siteLink: "https://reflectyr.vercel.app/",
  },
  {
    id: 6,
    title: "Food Xpiry: AI-Powered Grocery Expiration Tracker",
    type: "Hobby",
    tag: "AI Integration",
    workInProgress: true,
    image: "/images/expirty-screenshot-aug11.png",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "PostgreSQL (Neon)",
      "Prisma",
      "Anthropic AI API",
    ],
    createdDate: "2025",
    description:
      "Grocery tracker that reduces food waste using USDA FoodKeeper data and Anthropic API shelf-life estimates. Users log items, get storage tips and track expiration dates with PostgreSQL persistence via Neon.",
    githubLink: "https://github.com/tbrown034/food-xpiry",
    siteLink: "https://food-xpiry.vercel.app/",
  },
  {
    id: 7,
    title: "Caught Up Yet: Spoiler-Free Sports Chat",
    type: "Hobby",
    tag: "Real-Time & Auth",
    workInProgress: true,
    image: null,
    technologies: [
      "Next.js",
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Supabase",
      "PostgreSQL",
    ],
    createdDate: "2026",
    description:
      "Spoiler-free sports app for fans watching games on delay. Create rooms, invite friends and family and chat about games without scores being revealed. Filters alerts by team and sport with Supabase auth and real-time PostgreSQL.",
    githubLink: "https://github.com/tbrown034/caught-up-yet",
    siteLink: "https://caught-up-yet.vercel.app",
  },
];
