// Demo projects for /demos page - prospective employer showcase

export const demoProjects = [
  {
    id: 1,
    title: "Keith Brown DDS",
    subtitle: "Production Dental Practice Site + Admin Dashboard",
    oneLiner:
      "Built and manage a production dental practice website and its protected admin dashboard. The public site drives patient bookings through SEO and a $2K/month Google Ads campaign I optimized to triple new patient volume. The admin side is a custom finance and analytics dashboard behind Clerk auth.",
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Google Ads",
      "Python",
      "Clerk Auth",
      "REST API",
      "Nodemailer",
    ],
    screenshots: {
      desktopLight: "/images/demos/kab-dentist-desktop-light.png",
      desktopDark: "/images/demos/kab-dentist-desktop-dark.png",
      mobileLight: "/images/demos/kab-dentist-mobile-light.png",
      mobileDark: "/images/demos/kab-dentist-mobile-dark.png",
    },
    displayUrl: "keithbrowndds.com",
    siteLink: "https://keithbrowndds.com/",
    githubLink: null,
    arcadeLink: "https://demo.arcade.software/MFfJGhg8szhJEzdXfKAl",
  },
  {
    id: 2,
    title: "News Pulse",
    subtitle: "OSINT Geopolitical Awareness Dashboard",
    oneLiner:
      "An OSINT-style geopolitical awareness dashboard that aggregates 478 verified sources across RSS, Bluesky, Telegram, Reddit and YouTube. Features map-based monitoring, surge detection and tiered AI summarization via Claude.",
    technologies: [
      "Next.js",
      "TypeScript",
      "Anthropic API",
      "RSS",
      "Bluesky API",
      "Tailwind CSS",
    ],
    screenshots: {
      desktopLight: "/images/demos/news-alert-desktop-light.png",
      desktopDark: "/images/demos/news-alert-desktop-dark.png",
      mobileLight: "/images/demos/news-alert-mobile-light.png",
      mobileDark: "/images/demos/news-alert-mobile-dark.png",
    },
    displayUrl: "news-alert-eta.vercel.app",
    siteLink: "https://news-alert-eta.vercel.app",
    githubLink: "https://github.com/tbrown034/news-alert",
    arcadeLink: "https://demo.arcade.software/DQJYZcPvDYwwJgG9rnsn",
  },
  {
    id: 3,
    title: "AI Model Arena",
    subtitle: "Side-by-Side AI Model Comparison Tool",
    oneLiner:
      "A side-by-side AI comparison tool that sends one prompt to Claude, GPT, Gemini and Grok simultaneously. Includes AI-powered peer ranking, real-time cost tracking and a Fast vs. Frontier mode toggle.",
    technologies: [
      "Next.js 16",
      "TypeScript",
      "Anthropic API",
      "OpenAI API",
      "Google Gemini API",
      "Grok API",
    ],
    screenshots: {
      desktopLight: "/images/demos/ai-model-arena-desktop-light.png",
      desktopDark: "/images/demos/ai-model-arena-desktop-dark.png",
      mobileLight: "/images/demos/ai-model-arena-mobile-light.png",
      mobileDark: "/images/demos/ai-model-arena-mobile-dark.png",
    },
    displayUrl: "ai-model-arena-umber.vercel.app",
    siteLink: "https://ai-model-arena-umber.vercel.app",
    githubLink: "https://github.com/tbrown034/ai-model-arena",
    arcadeLink: "https://demo.arcade.software/s74PPWIPHAz3oqf084ZB",
  },
  {
    id: 4,
    title: "sort(id)",
    subtitle: "Media Ranking and Sharing Platform",
    oneLiner:
      "A media ranking platform where users create and share ranked lists of movies, TV, books, podcasts and anime. Built with drag-and-drop interfaces, TMDB and Open Library API integrations and PostgreSQL persistence.",
    technologies: [
      "Next.js 16",
      "Tailwind CSS 4",
      "PostgreSQL (Neon)",
      "TMDB API",
      "NextAuth.js",
    ],
    screenshots: {
      desktopLight: "/images/demos/reflectyr-desktop-light.png",
      desktopDark: "/images/demos/reflectyr-desktop-dark.png",
      mobileLight: "/images/demos/reflectyr-mobile-light.png",
      mobileDark: "/images/demos/reflectyr-mobile-dark.png",
    },
    displayUrl: "reflectyr.vercel.app",
    siteLink: "https://reflectyr.vercel.app/",
    githubLink: "https://github.com/tbrown034/reflect-yr",
    arcadeLink: "https://demo.arcade.software/nj2UXJN7mHlsGnbwcO9l",
  },
  {
    id: 5,
    title: "Second Brain v2",
    subtitle: "Local Knowledge Base with Vector Search",
    oneLiner:
      "A local knowledge base with 200K+ records built from texts, emails, articles, ChatGPT exports, photos and DNA data. TypeScript and Python pipelines handle ingestion, deduplication and vector search via LanceDB and Ollama.",
    technologies: [
      "TypeScript",
      "Python",
      "PostgreSQL",
      "LanceDB",
      "Ollama",
      "Playwright",
    ],
    screenshots: {
      desktopLight: "/images/demos/second-brain-desktop-light.png",
      desktopDark: null,
      mobileLight: null,
      mobileDark: "/images/demos/second-brain-mobile-dark.png",
    },
    siteLink: null,
    githubLink: null,
    arcadeLink: null,
  },
  {
    id: 6,
    title: "Food Xpiry",
    subtitle: "AI-Powered Grocery Expiration Tracker",
    oneLiner:
      "A grocery management app that helps reduce food waste. Users log groceries and get AI-powered shelf-life estimates, storage tips and expiration tracking via the Anthropic API.",
    technologies: [
      "Next.js",
      "TypeScript",
      "PostgreSQL (Neon)",
      "Prisma",
      "Anthropic AI API",
    ],
    screenshots: {
      desktopLight: "/images/demos/my-expiry-desktop-light.png",
      desktopDark: "/images/demos/my-expiry-desktop-dark.png",
      mobileLight: "/images/demos/my-expiry-mobile-light.png",
      mobileDark: "/images/demos/my-expiry-mobile-dark.png",
    },
    displayUrl: "food-xpiry.vercel.app",
    siteLink: "https://food-xpiry.vercel.app/",
    githubLink: "https://github.com/tbrown034/food-xpiry",
    arcadeLink: null,
  },
  {
    id: 7,
    title: "StuddyBuddy",
    subtitle: "AI Study Platform for Web Developers",
    oneLiner:
      "An AI-powered study platform for web developers. Pick a tech stack and skill level to get interactive quiz sessions powered by GPT-4o Mini alongside curated documentation links.",
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "OpenAI API",
      "Tailwind CSS 4",
    ],
    screenshots: {
      desktopLight: "/images/demos/study-buddy-desktop-light.png",
      desktopDark: "/images/demos/study-buddy-desktop-dark.png",
      mobileLight: "/images/demos/study-buddy-mobile-light.png",
      mobileDark: "/images/demos/study-buddy-mobile-dark.png",
    },
    displayUrl: "studdy-buddy-rho.vercel.app",
    siteLink: "https://studdy-buddy-rho.vercel.app/",
    githubLink: "https://github.com/tbrown034/study-buddy",
    arcadeLink: null,
  },
];
