// Demo projects for /projects page - prospective employer showcase

export const demoProjects = [
  {
    id: 9,
    title: "Open Cabinet",
    slug: "open-cabinet",
    subtitle: "Financial Disclosure Tracker for U.S. Executive Branch",
    oneLiner: [
      "Financial disclosure tracker covering 617 pages and $2.9B in assets across U.S. executive branch officials. Parses OGE filings into searchable, structured data with interactive D3.js visualizations.",
      "Built with Next.js and React on Tailwind CSS. Designed to make public financial disclosures accessible and transparent for journalists and researchers.",
    ],
    highlights: [
      "617 pages of financial disclosures parsed and structured",
      "$2.9B in assets tracked across executive branch officials",
      "Interactive D3.js visualizations for asset breakdowns",
      "Searchable database of OGE financial filings",
      "Built for journalists and accountability researchers",
    ],
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "D3.js",
    ],
    screenshots: {
      desktopLight: "/images/demos/open-cabinet-desktop-light.png",
      desktopDark: null,
      mobileLight: null,
      mobileDark: null,
    },
    displayUrl: "open-cabinet.org",
    siteLink: "https://open-cabinet.org",
    githubLink: "https://github.com/tbrown034/open-cabinet",
    arcadeLink: null,
  },
  {
    id: 10,
    title: "Capitol Releases",
    slug: "capitol-releases",
    subtitle: "Congressional Press Release Tracker and Analyzer",
    oneLiner: [
      "Congressional press release tracker that monitors all 100 U.S. senators. Aggregates official communications into per-senator intelligence reports with trend analysis.",
      "Built with Next.js and React on Tailwind CSS. Designed for journalists and policy researchers tracking legislative messaging and political positioning.",
    ],
    highlights: [
      "Tracks press releases from all 100 U.S. senators",
      "Per-senator intelligence reports with trend analysis",
      "Aggregates official congressional communications",
      "Built for journalists and policy researchers",
    ],
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
    ],
    screenshots: {
      desktopLight: "/images/demos/capitol-releases-desktop-light.png",
      desktopDark: null,
      mobileLight: null,
      mobileDark: null,
    },
    displayUrl: "capitolreleases.com",
    siteLink: "https://capitolreleases.com",
    githubLink: "https://github.com/tbrown034/capitol-releases",
    arcadeLink: null,
  },
  {
    id: 1,
    title: "Keith Brown DDS",
    slug: "keith-brown-dds",
    subtitle: "Production Dental Practice Site + Admin Dashboard",
    oneLiner: [
      "Production dental practice site in Naperville that increased online bookings by 33%. I manage SEO and optimize a $2,000/month Google Ads campaign directly.",
      "Protected admin dashboard integrates GA4, CallRail and Google Business Profile analytics with real-time ad controls, a Python billing data pipeline, an AI chat interface and a blog CMS.",
    ],
    highlights: [
      "Increased new patient bookings by 33% after launch",
      "Manage $2,000/month Google Ads campaign with real-time bid controls",
      "Built Python billing data pipeline for automated financial reporting",
      "Integrated CallRail, GA4 and Google Business Profile analytics into admin dashboard",
      "AI chat interface powered by Claude for patient inquiries",
    ],
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Google Ads",
      "Python",
      "Clerk Auth",
      "REST API",
      "Nodemailer",
    ],
    screenshots: {
      desktopLight: "/images/demos/kab-dentist-desktop-light.png",
      desktopDark: "/images/demos/kab-dentist-desktop-dark.png",
      mobileLight: "/images/demos/kab-dentist-mobile-light.png",
      mobileDark: "/images/demos/kab-dentist-mobile-dark.png",
    },
    displayUrl: "keithbrowndds.com",
    siteLink: "https://keithbrowndds.com/",
    githubLink: null,
    arcadeLink: "https://demo.arcade.software/MFfJGhg8szhJEzdXfKAl",
  },
  {
    id: 2,
    title: "News Pulse",
    slug: "news-pulse",
    subtitle: "Real-Time News Intelligence Dashboard",
    oneLiner: [
      "Real-time news intelligence dashboard that aggregates breaking stories with geopolitical context, trending keywords and region filtering.",
      "Built with Next.js and React. Designed for journalists and researchers tracking fast-moving news cycles.",
    ],
    highlights: [
      "Aggregates breaking stories with geopolitical context",
      "Trending keyword extraction and analysis",
      "Region filtering for geographic focus",
      "Built for journalists and researchers",
    ],
    technologies: [
      "Next.js",
      "React",
    ],
    screenshots: {
      desktopLight: "/images/demos/news-alert-desktop-light.png",
      desktopDark: "/images/demos/news-alert-desktop-dark.png",
      mobileLight: "/images/demos/news-alert-mobile-light.png",
      mobileDark: "/images/demos/news-alert-mobile-dark.png",
    },
    displayUrl: "news-pulse.org",
    siteLink: "https://news-pulse.org",
    githubLink: "https://github.com/tbrown034/news-alert",
    arcadeLink: "https://demo.arcade.software/DQJYZcPvDYwwJgG9rnsn",
  },
  {
    id: 5,
    title: "Second Brain",
    slug: "second-brain",
    subtitle: "Personal Knowledge Base with AI Chat and Search",
    oneLiner: [
      "Processes 200,000+ personal records from a dozen data sources — texts, emails, articles, ChatGPT exports, photos and DNA data — through TypeScript data pipelines with deduplication and normalization.",
      "Features an AI chat assistant, semantic search and visualization dashboards. Built with React and Next.js on a Tauri desktop wrapper with Playwright-based data ingestion.",
    ],
    highlights: [
      "Processes 200,000+ records from a dozen data sources",
      "TypeScript data pipelines with deduplication and normalization",
      "AI chat assistant powered by Anthropic API",
      "Semantic search across the full archive",
      "Visualization dashboards for data exploration",
      "Tauri desktop wrapper for native app experience",
      "Playwright-based web scraping and automated data ingestion",
    ],
    technologies: [
      "TypeScript",
      "React",
      "Next.js",
      "Playwright",
      "Anthropic API",
    ],
    gallery: [
      { label: "Data", image: "/images/demos/second-brain-data.png" },
      { label: "About", image: "/images/demos/second-brain-about.png" },
      { label: "Todos", image: "/images/demos/second-brain-todos.png" },
      { label: "Calendar", image: "/images/demos/second-brain-calendar.png" },
    ],
    screenshots: {
      desktopLight: "/images/demos/second-brain-data.png",
      desktopDark: null,
      mobileLight: null,
      mobileDark: null,
    },
    siteLink: null,
    githubLink: null,
    arcadeLink: null,
  },
  {
    id: 3,
    title: "AI Model Arena",
    slug: "ai-model-arena",
    subtitle: "Side-by-Side AI Model Comparison Tool",
    oneLiner: [
      "A side-by-side AI comparison tool that sends one prompt to Claude, GPT, Gemini and Grok simultaneously.",
      "Includes AI-powered peer ranking, real-time cost tracking and a Fast vs. Frontier mode toggle.",
    ],
    highlights: [
      "Queries four LLM APIs simultaneously — Claude, GPT, Gemini and Grok",
      "AI-powered peer ranking system where models evaluate each other",
      "Real-time cost tracking per query across all providers",
      "Fast vs. Frontier mode toggle for speed and quality tradeoffs",
    ],
    technologies: [
      "Next.js 16",
      "TypeScript",
      "Anthropic API",
      "OpenAI API",
      "Google Gemini API",
      "Grok API",
    ],
    screenshots: {
      desktopLight: "/images/demos/ai-model-arena-desktop-light.png",
      desktopDark: "/images/demos/ai-model-arena-desktop-dark.png",
      mobileLight: "/images/demos/ai-model-arena-mobile-light.png",
      mobileDark: "/images/demos/ai-model-arena-mobile-dark.png",
    },
    displayUrl: "ai-model-arena-umber.vercel.app",
    siteLink: "https://ai-model-arena-umber.vercel.app",
    githubLink: null,
    arcadeLink: "https://demo.arcade.software/s74PPWIPHAz3oqf084ZB",
  },
  {
    id: 4,
    title: "sort(id)",
    slug: "sort-id",
    subtitle: "Media Ranking and Sharing Platform",
    oneLiner: [
      "A media ranking platform where users create and share ranked lists of movies, TV, books, podcasts and anime.",
      "Built with drag-and-drop interfaces, TMDB and Open Library API integrations and PostgreSQL persistence.",
    ],
    highlights: [
      "TMDB and Open Library API integration for movies, TV, books and anime",
      "Drag-and-drop ranking interfaces for custom list creation",
      "NextAuth.js authentication with PostgreSQL persistence via Neon",
      "Shareable ranked lists with public profile pages",
    ],
    technologies: [
      "Next.js 16",
      "Tailwind CSS 4",
      "PostgreSQL (Neon)",
      "TMDB API",
      "NextAuth.js",
    ],
    screenshots: {
      desktopLight: "/images/demos/reflectyr-desktop-light.png",
      desktopDark: "/images/demos/reflectyr-desktop-dark.png",
      mobileLight: "/images/demos/reflectyr-mobile-light.png",
      mobileDark: "/images/demos/reflectyr-mobile-dark.png",
    },
    displayUrl: "reflectyr.vercel.app",
    siteLink: "https://reflectyr.vercel.app/",
    githubLink: null,
    arcadeLink: "https://demo.arcade.software/nj2UXJN7mHlsGnbwcO9l",
  },
  {
    id: 8,
    title: "Caught Up Yet",
    slug: "caught-up-yet",
    subtitle: "Spoiler-Free Sports Chat for Delayed Viewers",
    oneLiner: [
      "Sports app for fans watching games on delay. Create rooms, invite friends and family and chat about games without scores being revealed.",
      "Filters alerts by team and sport with Supabase authentication and real-time PostgreSQL persistence. Built because my dad watches Cubs games on delay and we wanted to react together without spoilers.",
    ],
    highlights: [
      "Spoiler-free chat rooms for delayed game viewing",
      "Team and sport filtering for personalized alerts",
      "Supabase authentication with real-time PostgreSQL",
      "Built for a real use case — watching Cubs games on delay with family",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Supabase",
      "PostgreSQL",
    ],
    screenshots: {
      desktopLight: "/images/demos/caught-up-yet-desktop-light.png",
      desktopDark: "/images/demos/caught-up-yet-desktop-dark.png",
      mobileLight: "/images/demos/caught-up-yet-mobile-light.png",
      mobileDark: "/images/demos/caught-up-yet-mobile-dark.png",
    },
    displayUrl: "caught-up-yet.vercel.app",
    siteLink: "https://caught-up-yet.vercel.app",
    githubLink: "https://github.com/tbrown034/caught-up-yet",
    arcadeLink: null,
  },
  {
    id: 6,
    title: "Food Xpiry",
    slug: "food-xpiry",
    subtitle: "AI-Powered Grocery Expiration Tracker",
    oneLiner: [
      "Grocery management app that reduces food waste using USDA FoodKeeper data and Anthropic API shelf-life estimates.",
      "Users log items, get AI-powered storage tips and track expiration dates with PostgreSQL persistence via Neon.",
    ],
    highlights: [
      "USDA FoodKeeper data for government-sourced shelf-life baselines",
      "Anthropic API generates custom storage tips and expiration estimates",
      "PostgreSQL persistence via Neon with Prisma ORM",
      "Item logging with category-based expiration tracking",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "PostgreSQL (Neon)",
      "Prisma",
      "Anthropic AI API",
    ],
    screenshots: {
      desktopLight: "/images/demos/my-expiry-desktop-light.png",
      desktopDark: "/images/demos/my-expiry-desktop-dark.png",
      mobileLight: "/images/demos/my-expiry-mobile-light.png",
      mobileDark: "/images/demos/my-expiry-mobile-dark.png",
    },
    displayUrl: "food-xpiry.vercel.app",
    siteLink: "https://food-xpiry.vercel.app/",
    githubLink: "https://github.com/tbrown034/food-xpiry",
    arcadeLink: null,
  },
  {
    id: 7,
    title: "StuddyBuddy",
    slug: "studdy-buddy",
    subtitle: "AI Study Platform for Web Developers",
    oneLiner: [
      "An AI-powered study platform for web developers.",
      "Pick a tech stack and skill level to get interactive quiz sessions powered by GPT-4o Mini alongside curated documentation links.",
    ],
    highlights: [
      "GPT-4o Mini powers interactive quiz generation",
      "Tech stack selection — JavaScript, TypeScript, React, Next.js and more",
      "Skill level personalization from beginner to advanced",
      "Curated documentation links alongside each quiz session",
    ],
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "OpenAI API",
      "Tailwind CSS 4",
    ],
    screenshots: {
      desktopLight: "/images/demos/study-buddy-desktop-light.png",
      desktopDark: "/images/demos/study-buddy-desktop-dark.png",
      mobileLight: "/images/demos/study-buddy-mobile-light.png",
      mobileDark: "/images/demos/study-buddy-mobile-dark.png",
    },
    displayUrl: "studdy-buddy-rho.vercel.app",
    siteLink: "https://studdy-buddy-rho.vercel.app/",
    githubLink: "https://github.com/tbrown034/study-buddy",
    arcadeLink: null,
  },
];
