// Demo projects for /demos page - prospective employer showcase

export const demoProjects = [
  {
    id: 1,
    title: "Keith Brown DDS",
    subtitle: "Production Dental Practice Site + Admin Dashboard",
    oneLiner: [
      "Production dental practice site in Naperville that increased online bookings by 33%. I manage SEO and optimize a $2,000/month Google Ads campaign directly.",
      "Protected admin dashboard integrates GA4, CallRail and Google Business Profile analytics with real-time ad controls, a Python billing data pipeline, an AI chat interface and a blog CMS.",
    ],
    highlights: [
      "Increased new patient bookings by 33% after launch",
      "Manage $2,000/month Google Ads campaign with real-time bid controls",
      "Built Python billing data pipeline for automated financial reporting",
      "Integrated CallRail, GA4 and Google Business Profile analytics into admin dashboard",
      "AI chat interface powered by Claude for patient inquiries",
    ],
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Google Ads",
      "Python",
      "Clerk Auth",
      "REST API",
      "Nodemailer",
    ],
    screenshots: {
      desktopLight: "/images/demos/kab-dentist-desktop-light.png",
      desktopDark: "/images/demos/kab-dentist-desktop-dark.png",
      mobileLight: "/images/demos/kab-dentist-mobile-light.png",
      mobileDark: "/images/demos/kab-dentist-mobile-dark.png",
    },
    displayUrl: "keithbrowndds.com",
    siteLink: "https://keithbrowndds.com/",
    githubLink: null,
    arcadeLink: "https://demo.arcade.software/MFfJGhg8szhJEzdXfKAl",
  },
  {
    id: 2,
    title: "News Pulse",
    subtitle: "Open-Source News Intelligence Dashboard",
    oneLiner: [
      "An open-source news intelligence dashboard that aggregates verified sources across RSS, Bluesky, Telegram, Reddit and YouTube.",
      "Built on open-web principles, it features map-based monitoring, surge detection and tiered AI summarization via Claude.",
    ],
    highlights: [
      "Aggregates five source types — RSS, Bluesky, Telegram, Reddit and YouTube",
      "Map-based monitoring with geographic surge detection",
      "Tiered AI summarization via Anthropic Claude API",
      "Built on open-source intelligence (OSINT) principles",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "Anthropic API",
      "RSS",
      "Bluesky API",
      "Tailwind CSS",
    ],
    screenshots: {
      desktopLight: "/images/demos/news-alert-desktop-light.png",
      desktopDark: "/images/demos/news-alert-desktop-dark.png",
      mobileLight: "/images/demos/news-alert-mobile-light.png",
      mobileDark: "/images/demos/news-alert-mobile-dark.png",
    },
    displayUrl: "news-alert-eta.vercel.app",
    siteLink: "https://news-alert-eta.vercel.app",
    githubLink: "https://github.com/tbrown034/news-alert",
    arcadeLink: "https://demo.arcade.software/DQJYZcPvDYwwJgG9rnsn",
  },
  {
    id: 3,
    title: "AI Model Arena",
    subtitle: "Side-by-Side AI Model Comparison Tool",
    oneLiner: [
      "A side-by-side AI comparison tool that sends one prompt to Claude, GPT, Gemini and Grok simultaneously.",
      "Includes AI-powered peer ranking, real-time cost tracking and a Fast vs. Frontier mode toggle.",
    ],
    highlights: [
      "Queries four LLM APIs simultaneously — Claude, GPT, Gemini and Grok",
      "AI-powered peer ranking system where models evaluate each other",
      "Real-time cost tracking per query across all providers",
      "Fast vs. Frontier mode toggle for speed and quality tradeoffs",
    ],
    technologies: [
      "Next.js 16",
      "TypeScript",
      "Anthropic API",
      "OpenAI API",
      "Google Gemini API",
      "Grok API",
    ],
    screenshots: {
      desktopLight: "/images/demos/ai-model-arena-desktop-light.png",
      desktopDark: "/images/demos/ai-model-arena-desktop-dark.png",
      mobileLight: "/images/demos/ai-model-arena-mobile-light.png",
      mobileDark: "/images/demos/ai-model-arena-mobile-dark.png",
    },
    displayUrl: "ai-model-arena-umber.vercel.app",
    siteLink: "https://ai-model-arena-umber.vercel.app",
    githubLink: "https://github.com/tbrown034/ai-model-arena",
    arcadeLink: "https://demo.arcade.software/s74PPWIPHAz3oqf084ZB",
  },
  {
    id: 4,
    title: "sort(id)",
    subtitle: "Media Ranking and Sharing Platform",
    oneLiner: [
      "A media ranking platform where users create and share ranked lists of movies, TV, books, podcasts and anime.",
      "Built with drag-and-drop interfaces, TMDB and Open Library API integrations and PostgreSQL persistence.",
    ],
    highlights: [
      "TMDB and Open Library API integration for movies, TV, books and anime",
      "Drag-and-drop ranking interfaces for custom list creation",
      "NextAuth.js authentication with PostgreSQL persistence via Neon",
      "Shareable ranked lists with public profile pages",
    ],
    technologies: [
      "Next.js 16",
      "Tailwind CSS 4",
      "PostgreSQL (Neon)",
      "TMDB API",
      "NextAuth.js",
    ],
    screenshots: {
      desktopLight: "/images/demos/reflectyr-desktop-light.png",
      desktopDark: "/images/demos/reflectyr-desktop-dark.png",
      mobileLight: "/images/demos/reflectyr-mobile-light.png",
      mobileDark: "/images/demos/reflectyr-mobile-dark.png",
    },
    displayUrl: "reflectyr.vercel.app",
    siteLink: "https://reflectyr.vercel.app/",
    githubLink: null,
    arcadeLink: "https://demo.arcade.software/nj2UXJN7mHlsGnbwcO9l",
  },
  {
    id: 5,
    title: "Second Brain",
    subtitle: "Local Knowledge Base with Vector Search",
    oneLiner: [
      "Processes 200,000+ personal records — texts, emails, articles, ChatGPT exports, photos and notes — through TypeScript data pipelines with deduplication and normalization.",
      "LanceDB vector embeddings power semantic search across the full archive. A streaming chat assistant with 30+ tools runs on local Ollama models inside a Tauri desktop wrapper.",
    ],
    highlights: [
      "Processes 200,000+ records from texts, emails, articles, photos and notes",
      "TypeScript data pipelines with deduplication and normalization",
      "LanceDB vector embeddings powering semantic search across the full archive",
      "Streaming chat assistant with 30+ tools running on local Ollama models",
      "Tauri desktop wrapper for native app experience",
      "Eager execution optimization pattern for sub-second query response",
      "Playwright-based web scraping and automated data ingestion",
    ],
    technologies: [
      "TypeScript",
      "Python",
      "PostgreSQL",
      "LanceDB",
      "Ollama",
      "Playwright",
    ],
    gallery: [
      { label: "Data", image: "/images/demos/second-brain-data.png" },
      { label: "About", image: "/images/demos/second-brain-about.png" },
      { label: "Todos", image: "/images/demos/second-brain-todos.png" },
      { label: "Calendar", image: "/images/demos/second-brain-calendar.png" },
    ],
    screenshots: {
      desktopLight: "/images/demos/second-brain-data.png",
      desktopDark: null,
      mobileLight: null,
      mobileDark: null,
    },
    siteLink: null,
    githubLink: null,
    arcadeLink: null,
  },
  {
    id: 6,
    title: "Food Xpiry",
    subtitle: "AI-Powered Grocery Expiration Tracker",
    oneLiner: [
      "Grocery management app that reduces food waste using USDA FoodKeeper data and Anthropic API shelf-life estimates.",
      "Users log items, get AI-powered storage tips and track expiration dates with PostgreSQL persistence via Neon.",
    ],
    highlights: [
      "USDA FoodKeeper data for government-sourced shelf-life baselines",
      "Anthropic API generates custom storage tips and expiration estimates",
      "PostgreSQL persistence via Neon with Prisma ORM",
      "Item logging with category-based expiration tracking",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "PostgreSQL (Neon)",
      "Prisma",
      "Anthropic AI API",
    ],
    screenshots: {
      desktopLight: "/images/demos/my-expiry-desktop-light.png",
      desktopDark: "/images/demos/my-expiry-desktop-dark.png",
      mobileLight: "/images/demos/my-expiry-mobile-light.png",
      mobileDark: "/images/demos/my-expiry-mobile-dark.png",
    },
    displayUrl: "food-xpiry.vercel.app",
    siteLink: "https://food-xpiry.vercel.app/",
    githubLink: "https://github.com/tbrown034/food-xpiry",
    arcadeLink: null,
  },
  {
    id: 7,
    title: "StuddyBuddy",
    subtitle: "AI Study Platform for Web Developers",
    oneLiner: [
      "An AI-powered study platform for web developers.",
      "Pick a tech stack and skill level to get interactive quiz sessions powered by GPT-4o Mini alongside curated documentation links.",
    ],
    highlights: [
      "GPT-4o Mini powers interactive quiz generation",
      "Tech stack selection — JavaScript, TypeScript, React, Next.js and more",
      "Skill level personalization from beginner to advanced",
      "Curated documentation links alongside each quiz session",
    ],
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "OpenAI API",
      "Tailwind CSS 4",
    ],
    screenshots: {
      desktopLight: "/images/demos/study-buddy-desktop-light.png",
      desktopDark: "/images/demos/study-buddy-desktop-dark.png",
      mobileLight: "/images/demos/study-buddy-mobile-light.png",
      mobileDark: "/images/demos/study-buddy-mobile-dark.png",
    },
    displayUrl: "studdy-buddy-rho.vercel.app",
    siteLink: "https://studdy-buddy-rho.vercel.app/",
    githubLink: "https://github.com/tbrown034/study-buddy",
    arcadeLink: null,
  },
];
